### ISSUE TITLE
Investigar modelos de votación online

### ISSUE THREAD

**Issue by Legutier** [CEEINF-UTFSM/ceeinf-web-backend#2]
Parte de los requerimientos de CEEINF Web es contar con un sistema de votaciones para los alumnos del departamento de informática de la Universidad Técnica Federico Santa María.

Para ello se requiere un paso de investigación inicial sobre el SOA de los sistemas de votación existentes y ver que carácterticas, ventajas y desventajas poseen cada uno.

Este será el primer paso para llevar a cabo el proyecto de votaciones.

**Comment by Legutier** [comment]
Cómo vamos con esto?

**Comment by MatiaCornejo** [comment]
Buenas tardes, he encontrado algunos metodos tales como **FIRMAS OCULTAS** , **CONTEO SECRETO** y **MIXNET**, todos propuesto hace bastante tiempo y hay suficiente información en internet, adjunto [paper](https://www.researchgate.net/publication/315599961_EL_VOTO_ELECTRONICO_Y_RETOS_CRIPTOGRAFICOS_RELACIONADOS), es un tanto teórico y entrega una buena introducción a estos metodos mencionados. 
En base a lo conversado, seria ideal implementar cifrados de llave publica y privada, conocido como cifrado de extremo a extremo [LINK](https://ssd.eff.org/es/module/una-mirada-en-profundidad-al-cifrado-de-extremo-extremo-%C2%BFc%C3%B3mo-funcionan-los-sistemas-de) y variantes de este mismo como PGP, utilizado comunmente en correos electronicos de alta confidencialidad, adjunto [LINK ](https://hardzone.es/reportajes/que-es/pgp-pretty-good-privacy/) de breve explicación de este mismo.

**Comment by AnakinBellakito** [comment]
Hola,
un buen sistema de votacion nesecita.
-Privacidad
-verificacion : individual(democracia liquida) y publica 
-alta eficacia
-robustez o seguridad

El metodo mas seguro de votacion es via blockchain pero dado que su implementacion es dificil y no somos una entidad publica o que se pueda obtener una ganancia monetariaalterando el sistema de votos podriamos optar por otro metodo, en cualquier caso
Una forma de implementarlos seria:
-Contratos inteligentes --> en base a Ethereum.
              Algunos framework a usar en el contrato inteligente serian Exonum(rust),Quorum(c,js), geth(c,js)

Fuente: https://skemman.is/bitstream/1946/31161/1/Research-Paper-BBEVS.pdf

**Comment by MatiaCornejo** [comment]
> Hola,
> un buen sistema de votacion nesecita.
> -Privacidad
> -verificacion : individual(democracia liquida) y publica 
> -alta eficacia
> -robustez o seguridad
> 
> El metodo mas seguro de votacion es via blockchain pero dado que su implementacion es dificil y no somos una entidad publica o que se pueda obtener una ganancia monetariaalterando el sistema de votos podriamos optar por otro metodo, en cualquier caso
> Una forma de implementarlos seria:
> -Contratos inteligentes --> en base a Ethereum.
>               Algunos framework a usar en el contrato inteligente serian Exonum(rust),Quorum(c,js), geth(c,js)
> 
> Fuente: https://skemman.is/bitstream/1946/31161/1/Research-Paper-BBEVS.pdf
> 
> 
> 

Si bien block chain es una buena alternativa al igual que ethereum y todo lo demás que mensionas, habría que medir el requerimiento de hardware que implica implementar este método, buen aporte

**Comment by MatiaCornejo** [comment]
Buenas, buscando alternativas, pense en que quizás el modelo de votación no deberia ser tan complicado, si lo que interesa es validar la veracidad del usuario, por lo que buscando segundos factores de autentificacion, encontré el autentificador de google y una api muy sencilla, https://authenticatorapi.com/, 
## Primero se debe parear el autentificador y la api
https://www.authenticatorApi.com/pair.aspx?AppName=<nombredescriptivo>&AppInfo=<infousuario>&SecretCode=<codigounicoporusuario>
## Validar codigo
https://www.authenticatorApi.com/Validate.aspx?Pin=<codigousuario>&SecretCode=<codigounicoporusuario>
De esta forma la segunda request entrega True o False dependiendo si el segundo factor corresponde al usuario o no.

**Comment by Landvaettir** [comment]
Resuelta en 1 hora
