### ISSUE TITLE
Recopilar información de carrera - Toma de ramos y postulaciones a ayudantías

### ISSUE THREAD

**Issue by Mxi-C0de** [CEEINF-UTFSM/ceeinf-web-backend#6]

**Comment by Mxi-C0de** [comment]
Hasta el momento se tiene con cierta información de la Toma de ramos a través de SIGA, donde en particular se tiene dudas acerca de la 2da etapa de este proceso.

Consta de 3 etapas:
- 1ra etapa: Cupos seleccionados por prioridad académica. Se seleccionan los ramos que se quieren tomar junto al respectivo paralelo.
- 2da etapa: Funciona de manera similar a la anterior. Si no se queda seleccionado en la 1ra etapa, ahora es cuando (**Información no muy segura**)
- 3ra etapa: 'Por orden de llegada', quien vaya inscribiendo va quedando hasta que se llenen los cupos.

-Maximiliano Tapia-

**Comment by Legutier** [comment]
Respecto a esto, por favor poner las fuentes de donde se encontró por favor.

**Comment by Mxi-C0de** [comment]
Obtuve información por medio de preguntas hechas a mi madrina de la carrera. Sin embargo, indagando mas a fondo encontré este apartado donde se explican más cosas adicionales:
https://usmtransparente.usm.cl/docs/informaciones/Manual%20Proceso%20de%20Matricula%20e%20Inscripcion%20de%20Asignaturas.pdf
EDIT:
Encontré otra fuente de información respecto a la inscripción de asignaturas: http://direcciondeestudios.usm.cl/inscripcion/

**Comment by Mxi-C0de** [comment]
http://dea.usm.cl/eaa/curso/ : Información acerca del curso de Asistentes de aprendizaje (ayudantes). Dentro se encuentra también las normas de participación y certificación
http://dea.usm.cl/eaa/wp-content/uploads/2020/06/EAA-infografia.pdf : Implementación del curso para ayudantes

**Comment by LaTortugaR** [comment]
Ya se hizo el código con la información aportada.
