### ISSUE TITLE
Recopilar información de carrera - Malla interactiva

### ISSUE THREAD

**Issue by vicholp** [CEEINF-UTFSM/ceeinf-web-backend#7]
https://github.com/CsarMan/malla-interactiva

**Comment by VoidRayXX** [comment]
Deberíamos considerar el que tal vez no sea necesario integrar el proyecto, ya que la página web de la malla interactiva ya está muy bien diseñada, permitiendo a los usuarios calcular su prioridad y ver mallas de otras carreras. Encuentro que el tratar de equipar ese nivel, nos tomaría mucho tiempo en algo que sería solo "reinventar la rueda", aun más si consideramos que la mayoría de la gente ya está acostumbrada a la otra página. Lo que podríamos hacer es brindar un link a los usuarios.

**Comment by Legutier** [comment]
<iframe src="url de malla" style="height: .... " />

**Comment by vicholp** [comment]
> <iframe src="url de malla" style="height: .... " />

Desde un iframe, la malla puede acceder a su localStorage?

**Comment by Legutier** [comment]
> > <iframe src="url de malla" style="height: .... " />
> 
> Desde un iframe, la malla puede acceder a su localStorage?

el localstorage no es de la pagina, es del cliente

**Comment by Landvaettir** [comment]
Issue terminada!!
