### ISSUE TITLE
Recopilar información de carrera - Actas de asambleas y archivos de transparencia (estatutos, fondos, etc).

### ISSUE THREAD

**Issue by BayronValenzuela** [CEEINF-UTFSM/ceeinf-web-backend#8]
Se encontró una [carpeta de drive][0] donde está lo requerido.
### Contenidos
- Actas.
- Estatutos y Reglamentos.
- Transparencia CEEINF 2020.
- Charla introductoria a Madrinas y Padrinos.

### Pendiente
- Contactar al propietario
- Ver actualización del Drive

[0]: https://drive.google.com/drive/folders/1VP9dsG64jvT7kDsvTRWv-djyRnLb-Nmg?usp=sharing

**Comment by Legutier** [comment]
Tenemos la data actual, deberíamos crear una herramienta para que el CEEINF centralice la data en nuestra web.

**Comment by Legutier** [comment]
como hacer una API: https://www.django-rest-framework.org/
